"""add is_playoff to games

Revision ID: 291421ac0f1f
Revises: 61fb2f188c2b
Create Date: 2026-05-23 21:18:35.149181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '291421ac0f1f'
down_revision: Union[str, None] = '61fb2f188c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_playoff', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_playoff')
    # ### end Alembic commands ###
