"""add player_game_stats

Revision ID: 6a74ed0b7c9d
Revises: 291421ac0f1f
Create Date: 2026-05-24 17:24:21.218832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a74ed0b7c9d'
down_revision: Union[str, None] = '291421ac0f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('pass_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_completions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_yards', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_tds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('interceptions_thrown', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rush_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rush_yards', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rush_tds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('receptions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('receiving_yards', sa.Integer(), server_default='0', nullable=False),
    sa.Column('receiving_tds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fumbles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fumbles_lost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sacks_allowed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tackles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sacks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('interceptions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('forced_fumbles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fumble_recoveries', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    # ### end Alembic commands ###
